name: Docker image build and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          tags: shenggao/flask-demo:latest
  deploy:
    runs-on: ubuntu-latest
    needs: Docker-Build-Push
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [[ -n $(docker ps -q -f "name=^flask-demo$") ]]; then
               echo "好"
               docker container stop flask-demo
               docker image pull shenggao/flask-demo:latest
               docker container run -d --rm -p 5000:5000 --name flask-demo shenggao/flask-demo:latest
             else
               echo "不好"
               docker image pull shenggao/flask-demo:latest
               docker container run -d --rm -p 5000:5000 --name flask-demo shenggao/flask-demo:latest
             fi
